### ISSUE TITLE
basic doubt

### ISSUE THREAD

**Issue by rochadiego** [Luxxii/ns3-focal#1]
could you give me a example about how to provide the source via -v if my file is in home for example?

could you give me source code applicable to your image?

I'm trying 
`sudo docker run --rm -v /home/diego/Documents/Projetos/iot:/ns3/ns-allinone-3.31/ns-3.31 "luxii/ns3-focal" "./waf --run hello-simulator"`

and I receive
/bin/bash: ./waf: No such file or directory

sorry, I'm a beginner.

**Comment by Luxxii** [comment]
Here a small tutorial on how to add own scripts.

You can easily navigate most of the images by executing `docker run -it luxii/ns3-focal /bin/bash`. 

Your command line would then show something like: 
```
[<My Computer>]$ docker run -it luxii/ns3-focal /bin/bash
root@1c3d1b88e5ed:/ns3/ns-allinone-3.31/ns-3.31# 
```
You can then run `ll` `ls` `la`, `pwd` and all the other command you may need, to know what is going on inside this image :) 

---

Now on to building. I followed [this](https://www.nsnam.org/docs/release/3.30/tutorial/singlehtml/index.html#building-your-script) tutorial to test it out.

First, we need a  [soruce file](https://www.nsnam.org/docs/release/3.27/doxygen/first_8cc_source.html), which i have added on my local computer in: `home/user/project/mycode/first.cc`  (this can also be more complex than a single file). The tutorial mentions that those files need to be added into the `scratch`-folder. So lets add it, see if it exists,  build it and lastly execute `first.cc`s code:

```
[<My Computer>]$ docker run -it -v /home/user/project/mycode/:/ns3/ns-allinone-3.31/ns-3.31/scratch  luxii/ns3-focal /bin/bash

root@d66f2cb97220:/ns3/ns-allinone-3.31/ns-3.31# ls scratch/
first.cc

root@d66f2cb97220:/ns3/ns-allinone-3.31/ns-3.31# ./waf
Waf: Entering directory `/ns3/ns-allinone-3.31/ns-3.31/build'
[2810/2881] Compiling scratch/first.cc
[2841/2881] Linking build/scratch/first
Waf: Leaving directory `/ns3/ns-allinone-3.31/ns-3.31/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (10.011s)

root@d66f2cb97220:/ns3/ns-allinone-3.31/ns-3.31# ./waf --run scratch/first
Waf: Entering directory `/ns3/ns-allinone-3.31/ns-3.31/build'
Waf: Leaving directory `/ns3/ns-allinone-3.31/ns-3.31/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (1.698s)
At time 2s client sent 1024 bytes to 10.1.1.2 port 9
At time 2.00369s server received 1024 bytes from 10.1.1.1 port 49153
At time 2.00369s server sent 1024 bytes to 10.1.1.1 port 49153
At time 2.00737s client received 1024 bytes from 10.1.1.2 port 9
```

---

So far, this image can build and execute a custom script. Luckily `waf` can build the sources automatically, so that only one command (`./waf --run scratch/first`) needs to be executed. You can test this yourself.

For a one liner, not going into this image (via`/bin/bash`),  you can run the following: 

```
docker run -v /home/user/project/mycode/:/ns3/ns-allinone-3.31/ns-3.31/scratch luxii/ns3-focal "./waf --run scratch/first"
```

Giving you the following output:
```
Waf: Entering directory `/ns3/ns-allinone-3.31/ns-3.31/build'
[2810/2881] Compiling scratch/first.cc
[2841/2881] Linking build/scratch/first
Waf: Leaving directory `/ns3/ns-allinone-3.31/ns-3.31/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (8.527s)
At time 2s client sent 1024 bytes to 10.1.1.2 port 9
At time 2.00369s server received 1024 bytes from 10.1.1.1 port 49153
At time 2.00369s server sent 1024 bytes to 10.1.1.1 port 49153
At time 2.00737s client received 1024 bytes from 10.1.1.2 port 9
```

**Comment by rochadiego** [comment]
hey man, it works! :smiley:

thank you so much.

greetings from brazil. :brazil:
